spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: messages
      default:
        contentType: application/json

  application:
    name: publisher-service

server:
  port: 8020
