GET http://localhost:8080/signUp/confirmation/3
Accept: application/json

###Confirmation
POST http://localhost:8080/signUp
Content-Type: application/json

{ "email": "prusla@gmail.com",
  "password": "123456","passwordRepeat": "123456",
  "g-recaptcha-response": "1",
  "remember-me":"on"}
###Sign Up
