#!/bin/bash
#additional option inside scenario
set -euf -o pipefail
D=$(dirname $BASH_SOURCE)
source $D/.functions
trap "handle_exit" EXIT

fines_port=8082
host=localhost
hub_port=8080

hub_url=$host:$hub_port/hub/cards

current_date=1500197400000
user_id=20
longitude=51.7908562
latitude=54.962341

COMMAND="${1: }"

remoteCall() {
    curl -s $1?currentDate=$current_date -XGET -H 'userId:'$user_id -H "longitude: $longitude" -H "latitude: $latitude"
    printf '=%.0s' {1..100} && echo $1
}

case "$COMMAND" in
  simple_ind_call)
    _yellow independent call of service
    remoteCall $host:$fines_port
    ;;
  simple_hub_call)
    _yellow hub call
    remoteCall $hub_url
    ;;
  load)
    _yellow hub call
    ./$D/load/loader.sh load $hub_url?currentDate=$current_date $user_id $longitude $latitude ${@:2}
    ;;
  light_load)
    _yellow hub call
    ./$D/load/loader.sh light_load $hub_url?currentDate=$current_date $user_id $longitude $latitude
    ;;
  heavy_load)
    _yellow hub call
    ./$D/load/loader.sh heavy_load $hub_url?currentDate=$current_date $user_id $longitude $latitude
    ;;
  *)
    echo "use command [simple_ind_call|simple_hub_call|load|light_load|heavy_load|env|env_stop|env_restart|env_down|mongo_fill|boot]"
    no_status
    _done
  ;;
esac

